### ISSUE TITLE
Arow Keys Relocates Your Character

### ISSUE THREAD

**Issue by nitoygo** [sven-n/MuMain#108]
**Describe the bug**
Pressing Arow Keys Relocates Your Character

**To Reproduce**
1. Login character
2. Press any arrow key: → (right arrow),← (left arrow),↑ (top arrow),↓ (down arrow)
3. Notice the character slides to the direction of the arrow

**Expected behavior**
Arrow keys should not move the character

**Comment by sven-n** [comment]
It's a debug build feature ;)

**Comment by nitoygo** [comment]
I see. False alarm. Closing ticket.
