### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by 601743012** [sven-n/MuMain#33]
Hello, I am a MU fan. I am very excited to see your project. I am willing to help you with testing or finding bugs, but I am currently facing a problem: I have built the project according to the method you provided, but there is a problem with You are disconnected from the server during runtime. My server is openmu, and other clients can connect normally. I suspect there is a problem with my build method. Could you explain the project build and subsequent operations in detail? Thank you very much!

**Comment by 601743012** [comment]
![1728561838323](https://github.com/user-attachments/assets/ad0a4c4d-98e8-4581-b310-19878cf35865)

**Comment by 601743012** [comment]
![1728562439721](https://github.com/user-attachments/assets/4b8bab88-040e-469b-9fbf-fd99fc10c137)

**Comment by sven-n** [comment]
Hi, did you install and run OpenMU in the latest version? In this case, there should be two connect servers available - one for port 44405 (original client) and 44406 (this client). Is this the case? You can check this on the admin panel of OpenMU. If 44406 is missing, you can connect to 44405 with starting parameters `/u127.127.127.127 /p44405`, too.

**Comment by 601743012** [comment]
> Hi, did you install and run OpenMU in the latest version? In this case, there should be two connect servers available - one for port 44405 (original client) and 44406 (this client). Is this the case? You can check this on the admin panel of OpenMU. If 44406 is missing, you can connect to 44405 with starting parameters `/u127.127.127.127 /p44405`, too.

Thank you for your reply! I have downloaded the latest OPENMU server and the game is now running smoothly. 
However, I have encountered a bug: When creating a new character, regardless of whether I choose Dark Knight or Elf, after clicking OK, the character's appearance and profession both display as Wizard. It only returns to normal after I have entered the game once. Since I have limited programming knowledge, what files, logs, images, or other information should I upload to help you locate this bug?

**Comment by 601743012** [comment]
Emmm, one more thing, it seems that the Combo-system for the Knight class is not functioning properly, which might be an issue on the server side. I noticed that you addressed it on Oct 19, 2022, but I found it unusable during my test today. My character is a Blade Knight (Test Account: test300) and the skill release order is: First: Cyclone, Second: Rageful Blow, Third: Death Stab.
![image](https://github.com/user-attachments/assets/6ffd130c-fa88-459f-ac2e-0abb6b262cda)
![image](https://github.com/user-attachments/assets/cbeb2803-b0bc-4771-99a2-512674759805)
![image](https://github.com/user-attachments/assets/5ee46931-178d-48a0-83a3-ceace3d12992)

**Comment by sven-n** [comment]
> Thank you for your reply! I have downloaded the latest OPENMU server and the game is now running smoothly. However, I have encountered a bug: When creating a new character, regardless of whether I choose Dark Knight or Elf, after clicking OK, the character's appearance and profession both display as Wizard. It only returns to normal after I have entered the game once. Since I have limited programming knowledge, what files, logs, images, or other information should I upload to help you locate this bug?

I have fixed it in the latest commit https://github.com/sven-n/MuMain/commit/4ff3cec63f7a001d46587e8541b35690169ec8eb
