### ISSUE TITLE
Dark Raven continues to level up when equipped but not enough charisma

### ISSUE THREAD

**Issue by nitoygo** [sven-n/MuMain#36]
Need to prevent the dark raven from accumulating exp (or at least be capped at the maximum exp - 1) when the owner does not have enough charisma required for the next level of the pet

**Comment by sven-n** [comment]
Okay, that's a server (OpenMU) issue ;)

**Comment by nitoygo** [comment]
Got it. Do I make an issue in OpenMU to track this?

**Comment by nitoygo** [comment]
Nevermind, just checked the ticket already in OpenMU, thanks man!
