### ISSUE TITLE
Change Class DK->BK needs switch char to reflect

### ISSUE THREAD

**Issue by nitoygo** [sven-n/MuMain#39]
Did my first change job quest, talked with Sebina, gave the quest items, but after everything, the class name (at the top of char panel (when pressing c below the character name) remained 'Dark Knight', I needed to switch characters in order to have the class name reflected.

**Comment by sven-n** [comment]
Thanks for reporting. Fixed with https://github.com/sven-n/MuMain/commit/1c6940714eb816a2cbe925d79e743c75702f57bb.

**Comment by nitoygo** [comment]
noob question, how did shifting by 3 resolved the issue?

**Comment by sven-n** [comment]
I did some changes recently to the network protocol. The old code shifted the char class by 3, I removed that everywhere to clean it up. However, I forgot that in the quest packets it's still shifted by 3. I didn't want to introduce a new packet structure just for this little thing, so I added the shifting again on client side for this quest packet.
