### ISSUE TITLE
Ancient items appear as normal

### ISSUE THREAD

**Issue by nitoygo** [sven-n/MuMain#43]
Steps:
* Login using 'ancient'
* select any character and enter the game
* visually inspect the character's appearance
* open inventory, check/hover to equipment items

Result:
* the characters equipments look normal (no aura, no special hue to the items)
* in the inventory, the items are normal (no options).

Note: works ok when tested using the official 6.3 client

**Comment by sven-n** [comment]
Fixed with https://github.com/MUnique/OpenMU/commit/0b4ee8b5b5589b8319fa1d699228a75aee0b5ace.

**Comment by nitoygo** [comment]
Hello @sven-n , there was a regression encountered with this fix.
The items dropping that are supposed to be Excellent, now drops as normal.  
The excellent items I looted yesterday too, became normal in my inventory.

(It did fix the issue with the appearance of the ancient sets though)
