### ISSUE TITLE
Regression with MUnique/OpenMU@0b4ee8b

### ISSUE THREAD

**Issue by nitoygo** [sven-n/MuMain#46]
Hello @sven-n , there was a regression encountered with this fix in OpenMU: https://github.com/MUnique/OpenMU/commit/0b4ee8b5b5589b8319fa1d699228a75aee0b5ace  

The items dropping that are supposed to be Excellent, now drops as normal.
The excellent items I looted yesterday too, became normal in my inventory.

It did fix the issue with the appearance of the ancient sets though (https://github.com/sven-n/MuMain/issues/43)

**Comment by nitoygo** [comment]
[Update] 
There are actual drops of excellent items, but there are items too low level items for the map that are supposed to be excellent but are normal.

Example:
map: Tarkan
drop: War Hammer (normal)
expected: War Hammer (excellent)

Note: normal low level such as War Hammer should not drop in higher level maps unless they are excellent

**Comment by sven-n** [comment]
Oh, sorry and thanks for reporting that. I'll fix it as soon as I'm back home 😅

**Comment by nitoygo** [comment]
@sven-n, I can confirm that this particular line of code was executed:
![image](https://github.com/user-attachments/assets/e1838120-373c-4536-837e-4af6cf675014)
however, while some items with the added options actually become excellent when dropped in the client,
some items, remain normal (even if that line was executed)

I noticed that it mostly happens when the item has no JOL option.
So most like related to the serializer.

**Comment by nitoygo** [comment]
Hello @sven-n, this patch in OpenMU seem to fix this issue:
https://github.com/MUnique/OpenMU/pull/506

Could you confirm this patch?

**Comment by sven-n** [comment]
Thank you :)
