### ISSUE TITLE
Unequipping Gear/Pet does not reflect on other player's view

### ISSUE THREAD

**Issue by nitoygo** [sven-n/MuMain#47]
**Describe the bug**
Unequipping Gear/Pet does not reflect on other player

**To Reproduce**
1. Login 2 players, Player1 and Player2, Player1 with a pet (or any gear equipped)
2. Player1: Equip Fenrir
3. // Player2 can see Player1 ride the fenrir
4. Player1: Unequip Fenrir
5. // Player2 still see Player1 on a fenrir

**Expected behavior**
From Player2's POV, the fenrir should no longer be visible
(Also applies to gear such as armor, wings, etc.)

**Additional Context**
In client side, 0xFF is used to detect if the equipment is to be removed.
However, from the logs, the ItemGroup value sent by the server is using the original value of the item.

**Comment by nitoygo** [comment]
Filed similar bug to OpenMU (since this may also be a server issue)
https://github.com/MUnique/OpenMU/issues/509

**Comment by sven-n** [comment]
Closed because it's a server issue.
