### ISSUE TITLE
Consuming Ale causes exception

### ISSUE THREAD

**Issue by nitoygo** [sven-n/MuMain#48]
**Describe the bug**
Consuming Ale causes exception

**To Reproduce**
1. Buy Ale
2. Consume it
3. Voila!
![image](https://github.com/user-attachments/assets/f499cb8d-38d0-44ff-afd6-8da68d4281c0)

**Expected behavior**
Should be able to consume without any problem, gain additional attack speed

**Comment by sven-n** [comment]
It will be fixed with https://github.com/MUnique/OpenMU/pull/502
Commit: https://github.com/MUnique/OpenMU/pull/502/commits/4761521711bc029f3691979b46ab3ff0c3672e2b
