### ISSUE TITLE
where is the souces of ItemTooltip ?

### ISSUE THREAD

**Issue by buuug7** [sven-n/MuMain#5]
did you know where is the source of ItemTooltip ? your answer is import for me and thanks.

**Comment by sven-n** [comment]
https://github.com/sven-n/MuMain/blob/65caee65b4684568e2f1244363f0652a9221aa2d/Source%20Main%205.2/source/NewUIInventoryCtrl.cpp#L1431

**Comment by buuug7** [comment]
@sven-n Thanks, i want contribute to this codebase, you welcome ?

**Comment by sven-n** [comment]
Sure, please enter our discord, so we can coordinate: https://discord.gg/NZZyGrMT
