### ISSUE TITLE
Skill Nova not work

### ISSUE THREAD

**Issue by sonniit92** [sven-n/MuMain#78]
I left the code to fix the bug when using nova skill that I found in your code.

In **void Attack(CHARACTER* c)**

Remove this
if (MouseLButtonPush || MouseLButton)
{
		MouseLButtonPush = false;
		Success = true;
}
	
In **int ExecuteSkill(CHARACTER* c, int Skill, float Distance);**

iSkillIndex = g_pSkillList->GetSkillIndex(Skill); will return an invalid value for the skill and thus the skill cannot be used.

Fix by

if (Skill == AT_SKILL_BLAST_HELL_BEGIN)
{
	if (g_pSkillList->GetSkillIndex(AT_SKILL_BLAST_HELL) == -1)
	{
		return 0;
	}
	iSkillIndex = g_pSkillList->GetSkillIndex(AT_SKILL_BLAST_HELL);
}
else
{
	iSkillIndex = g_pSkillList->GetSkillIndex(Skill);
	if (iSkillIndex == -1)
	{
		return 0;
	}
}

**Comment by nitoygo** [comment]
Nice. But, why not send a PR?

**Comment by sonniit92** [comment]
> Nice. But, why not send a PR?

I don't use github much so there might be some functions I don't know about, it's a bug so I posted here.

**Comment by nitoygo** [comment]
Fixed in latest OpenMU+MuMain. Kindly close issue if you were able to verify this to be already working. Thanks!
