### ISSUE TITLE
FPS Drops when there are too many items/zen on the ground

### ISSUE THREAD

**Issue by nitoygo** [sven-n/MuMain#83]
In the following screenshot, the base FPS was 60.
It dropped to almost half when there's already too many items/zen on the ground:
![image](https://github.com/user-attachments/assets/abe9dbb8-bb5d-42ab-ac46-f87cf14b0228)

**Comment by sven-n** [comment]
What causes the fps drop is the high amount of coins on the ground. Each coin is rendered seperately 🙄
See ZzzObject.cpp, method RenderItems:
```cpp
if (o->Type == MODEL_POTION + 15) // Zen
{
    vec3_t Temp;
    VectorCopy(o->Position, Temp);
    int Count = (int)sqrtf((float)Items[i].Item.Level) / 2;
    if (Count < 3) Count = 3;
    if (Count > 80) Count = 80;
    for (int j = 1; j < Count; j++)
    {
        vec3_t Angle;
        float Matrix[3][4];
        vec3_t p, Position;
        Vector(0.f, 0.f, (float)(RandomTable[(i * 20 + j) % 100] % 360), Angle);
        Vector((float)(RandomTable[(i + j) % 100] % (Count + 20)), 0.f, 0.f, p);
        AngleMatrix(Angle, Matrix);
        VectorRotate(p, Matrix, Position);
        VectorAdd(Temp, Position, o->Position);
        RenderPartObject(o, o->Type, NULL, Light, o->Alpha, Items[i].Item.Level, Items[i].Item.ExcellentFlags, Items[i].Item.AncientDiscriminator, true, true, true);
    }
    VectorCopy(Temp, o->Position);
}
```

**Comment by sven-n** [comment]
@nitoygo Can you try if #93 improves the performance?

**Comment by sven-n** [comment]
I tried to do a comparison and it is indeed a bit faster. However, I get some lightning problems on some coin piles:

![grafik](https://github.com/user-attachments/assets/57ba8f1a-94f0-4e9c-9698-028ef812f9cf)

**Comment by nitoygo** [comment]
Cool, I get consistent FPS now with many zen on the ground:
![image](https://github.com/user-attachments/assets/675601df-11e6-4784-9719-32d1b3e1b895)

**Comment by sven-n** [comment]
Thanks for testing 😀
