### ISSUE TITLE
Add shadow for caper - MG, GM, Duel player

### ISSUE THREAD

**Issue by sonniit92** [sven-n/MuMain#94]
I previously shared the code to add shadow to Wing and it was improved by sven, I found that sven's code currently does not support MG characters or characters that are doing dueling and wearing cloaks behind. Here is the code to add them.

in void RenderLinkObject add this to end.

if (g_MapManager->World != WD_10HEAVEN && g_MapManager->InHellas() == FALSE && !g_Direction.m_CKanturu.IsMayaScene())
{
	switch (Type)
	{
	case MODEL_WING + 0:
	case MODEL_WING + 1:
	case MODEL_WING + 2:
	case MODEL_WING + 41:

	case MODEL_WING + 3:
	case MODEL_WING + 4:
	case MODEL_WING + 5:
	case MODEL_WING + 6:
	case MODEL_WING + 42:

	case MODEL_WING + 36:
	case MODEL_WING + 37:
	case MODEL_WING + 38:
	case MODEL_WING + 39:
	case MODEL_WING + 43:

	case MODEL_WING + 131:
	case MODEL_WING + 132:
	case MODEL_WING + 133:
	case MODEL_WING + 134:
	{
		b->RenderBodyShadow();
	}
	break;
	default:
		if (c->Object.m_pCloth)
		{
			b->RenderBodyShadow(-1, -1, -1, -1, o->m_pCloth, o->m_byNumCloth);
		}
		break;
	}

**Comment by sven-n** [comment]
Thank you :)
